import { Email, Name20, NickName20, Password16, Phone, SmsCode6 } from '@const/regexp';

export const userFormSchema: CxFormSchema[] = [
  {
    name: 'userName',
    required: true,
    maxLength: 20,
    minLength: 4,
    pattern: Name20,
    errorTip: { required: '用户名为必填项', maxlength: '用户名最大长度20', minlength: '用户名最小长度4', pattern: '无效的用户名' },
    label: '用户名',
    help: '用户登录名，长度不超过20个字符',
  },
  {
    name: 'password',
    required: true,
    maxLength: 16,
    minLength: 6,
    pattern: Password16,
    errorTip: { required: '请输入密码', maxlength: '密码最大长度16', minlength: '密码最小长度要求6个字符', pattern: '无效的密码' },
    label: '密码',
    help: '大小写字母、数字和符号的组合，长度在6-16位之间',
  },
  {
    name: 'confirm',
    required: true,
    maxLength: 16,
    minLength: 6,
    pattern: Password16,
    errorTip: {
      required: '请输入密码',
      maxlength: '密码最大长度16',
      minlength: '密码最小长度要求6个字符',
      pattern: '无效的密码',
      confirm: '两次输入密码不匹配',
    },
    label: '确认密码',
    help: '大小写字母、数字和符号的组合，长度在6-16位之间',
  },
  {
    name: 'nickName',
    maxLength: 20,
    pattern: NickName20,
    label: '昵称',
    tooltip: '你想让别人怎么称呼你？',
  },
  {
    name: 'email',
    maxLength: 30,
    label: '邮箱',
    pattern: Email,
    errorTip: '无效的邮箱格式',
  },
  {
    name: 'countryCode',
    required: true,
    custom: true,
    disabled: true,
  },
  {
    name: 'phoneNumber',
    required: true,
    pattern: Phone,
    divider: true,
    label: '手机号码',
    errorTip: '无效的手机号码',
    tooltip: '当前仅支持中国大陆地区手机号码注册',
    maxLength: 11,
    style: { width: 220 },
    help: '请输入1开头的11位数字手机号码',
  },
  {
    name: 'captcha',
    required: true,
    maxLength: 6,
    pattern: SmsCode6,
    label: '验证码',
    style: { width: 80 },
    errorTip: '输入获取的手机短信验证码',
    tooltip: '点击【获取验证码】',
    help: '正确输入手机号码后，获取6位数字短信验证码，有效期为5分钟\n开发模式下以999999代替',
  },
];
